#!python3

import sys
from pathlib import Path
from PIL import Image
from pyora import Project
from decompose.utils import images_to_ORA, palette_to_image
from decompose.decomposer import decompose
from decompose.dominants import get_dominant_colors

file_path = sys.argv[1]

path = Path(file_path)
palette_path = path.with_name(path.stem + "palette" + ".png")
ora_path = path.with_name(path.stem + ".ora")

im = Image.open(path)
palette = get_dominant_colors(im, 7)
images = decompose(im, palette)
project = Project.new(*images[0].size)
for i in range(len(images)):
    project.add_layer(images[i], "RGBA Layer " + str(i))

# save ora
project.save(ora_path)
print("ORA saved: " + str(ora_path))

# save palette
palette_to_image(palette).save(palette_path)
print("Palette saved: " + str(palette_path))
